;startMovie("i101", "afterMovie1")
;waitsignal("afterMovie1")
;startMovie("i102", "afterMovie2")
;waitsignal("afterMovie2")
;startMovie("i103", "afterMovie3")
;waitsignal("afterMovie3")
;startMovie("i104", "afterMovie4")
;waitsignal("afterMovie4")
;startMovie("i105", "afterMovie5")
;waitsignal("afterMovie5")
;startMovie("i106", "afterMovie6")
;waitsignal("afterMovie6")
;startMovie("i107", "afterMovie7")
;waitsignal("afterMovie7")
beginmissionhack("demo")
